"""added created_at to llm_personality nullable

Revision ID: 228a9aa3e827
Revises: c61aba44409c
Create Date: 2023-08-21 20:52:11.405396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '228a9aa3e827'
down_revision = 'c61aba44409c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_personality', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('llm_personality', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
