"""added personality table

Revision ID: 679e43c6108b
Revises: bff86c6c91cc
Create Date: 2023-03-18 18:59:15.854060

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679e43c6108b'
down_revision = 'bff86c6c91cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('books', sa.String(length=2000), nullable=False),
    sa.Column('handle', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('personality')
    # ### end Alembic commands ###
