"""added llm_personality table

Revision ID: c61aba44409c
Revises: 679e43c6108b
Create Date: 2023-08-21 20:28:05.670656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c61aba44409c'
down_revision = '679e43c6108b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_personality',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('llm_personality', sa.String(length=10000), nullable=False),
    sa.Column('handle', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_personality')
    # ### end Alembic commands ###
